model: hf.co/unsloth/Qwen3-32B-GGUF:Q4_K_XL
# model: devstral:24b
provider: ollama
providers:
  ollama:
    name: Ollama
    # baseURL: "http://localhost:11434/v1"
    baseURL: "http://pc.zoe:11434/v1"
    envKey: OLLAMA_API_KEY
history:
  maxSize: 1000
  saveHistory: true
  sensitivePatterns: []
