- hosts: localhost
  # become: true
  vars_files:
    - vars.yml
  tasks:
  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/.vimrc'
      dest: "{{lookup('env','HOME')}}/.vimrc" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/.vim_runtime'
      dest: "{{lookup('env','HOME')}}/.vim_runtime" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/.tmux.conf'
      dest: "{{lookup('env','HOME')}}/.tmux.conf" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/.tmux.conf.local'
      dest: "{{lookup('env','HOME')}}/.tmux.conf.local" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/.alacritty.yml'
      dest: "{{lookup('env','HOME')}}/.alacritty.yml" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zlogin'
      dest: "{{lookup('env','HOME')}}/.zlogin" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zlogout'
      dest: "{{lookup('env','HOME')}}/.zlogout" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zpreztorc'
      dest: "{{lookup('env','HOME')}}/.zpreztorc" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zprofile'
      dest: "{{lookup('env','HOME')}}/.zprofile" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zshenv'
      dest: "{{lookup('env','HOME')}}/.zshenv" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/runcoms/.zshrc'
      dest: "{{lookup('env','HOME')}}/.zshrc" 
      owner: "{{ theuser }}" 
      state: link   

  - name: Create a symbolic link
    ansible.builtin.file:
      src:  '{{ playbook_dir }}/p10k/.p10k.zsh'
      dest: "{{lookup('env','HOME')}}/.p10k.zsh" 
      owner: "{{ theuser }}" 
      state: link   

  - name: install and update brew
    community.general.homebrew:
      name: '{{ brew_pkgs }}' 
      state: present 
      update_homebrew: yes
      upgrade_all: yes

  - name: install and update brew casks
    community.general.homebrew_cask:
      name: '{{ brew_casks }}' 
      state: present 
      update_homebrew: yes
      upgrade_all: yes

  - name: clone prezto repo
    ansible.builtin.git:
      repo: https://github.com/sorin-ionescu/prezto.git
      dest: "{{lookup('env','HOME')}}"
      recursive: yes
    ignore_errors: yes 
  
  - name: install programs with asdf
    command: "asdf plugin-add '{{ asdf_pkgs }}'"
    loop: '{{ asdf_pkgs }}'

    # -name: asdf
