#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
        - country-mirror
        - arches: &id001
            - amd64
            - i386
          uri: http://archive.ubuntu.com/ubuntu/
        - arches: &id002
            - s390x
            - arm64
            - armhf
            - powerpc
            - ppc64el
            - riscv64
          uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
      - arches: *id001
        uri: http://security.ubuntu.com/ubuntu/
      - arches: *id002
        uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: zoe-ubuntu
    password: foo
    realname: zoe
    username: zoe
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ""
  locale: en_US.UTF-8
  network:
    ethernets:
      enp1s0:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
      - ptable: gpt
        path: /dev/vda
        wipe: superblock-recursive
        preserve: false
        name: ""
        grub_device: false
        id: disk-vda
        type: disk
      - device: disk-vda
        size: 1127219200
        wipe: superblock
        flag: boot
        number: 1
        preserve: false
        grub_device: true
        offset: 1048576
        path: /dev/vda1
        id: partition-0
        type: partition
      - fstype: fat32
        volume: partition-0
        preserve: false
        id: format-0
        type: format
      - device: disk-vda
        size: 51374981120
        wipe: superblock
        number: 2
        preserve: false
        offset: 1128267776
        path: /dev/vda2
        id: partition-1
        type: partition
      - fstype: ext4
        volume: partition-1
        preserve: false
        id: format-1
        type: format
      - path: /
        device: format-1
        id: mount-1
        type: mount
      - path: /boot/efi
        device: format-0
        id: mount-0
        type: mount
  timezone: America/New_York
  updates: security
  version: 1
