name: build-and-deploy-prod-on-main-push

env:
  NAMESPACE: prod

on:
  push:
    branches: 
      - main

jobs:
  docker:
    name: Build and push image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4
        # with:
        #   caCertificate: ${{ secrets.ZOE_ROOT_CA }}
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSL_CERT_SECRET: ${{ secrets.ZOE_ROOT_CA }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> "${GITHUB_ENV}"

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORTSHA=${calculatedSha}" >> "${GITHUB_ENV}"

      - name: Kaniko build arch
        uses: aevea/action-kaniko@master
        with:
          image: docker.io/virtualdisk/dotfiles
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: ${{ env.SHORTSHA }}
          cache: true
          cache_registry: docker.io/virtualdisk/dotfiles
          tag_with_latest: true
          strip_tag_prefix: v
          path: ./docker/arch

      - name: Kaniko build catalina
        uses: aevea/action-kaniko@master
        with:
          image: docker.io/virtualdisk/dotfiles
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: ${{ env.SHORTSHA }}
          cache: true
          cache_registry: docker.io/virtualdisk/dotfiles
          tag_with_latest: true
          strip_tag_prefix: v
          path: ./docker/arch
