name: Generate Workflows

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "44 7 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-and-push:
    uses: VirtualDisk/dotfiles/.github/workflows/build-and-push.yaml@main
    with:
      os: "${{ matrix.os }}"
      registry: "registry.zoe/zcr.io"
    secrets:
      registry_username: "${{ secrets.REGISTRY_ZOE_USERNAME }}"
      registry_password: "${{ secrets.REGISTRY_ZOE_PASSWORD }}"
    strategy:
      fail-fast: false
      matrix:
        os:
          - "arch"
          - "debian-trixie"
          - "fedora-41"
          - "macos-sonoma"
          - "ubuntu-noble"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
